In [1]:
import numpy as np

In [2]:
# 3. Perform the following operations on an array of mobile phones prices 6999, 7500,
# 11999, 27899, 14999, 9999.

In [4]:
# a. Create a 1d-array of mobile phones prices
price = [6999, 7500, 11999, 27899, 14999, 9999]
price

[6999, 7500, 11999, 27899, 14999, 9999]

In [12]:
# b. Convert this array to float type
array = np.array(price)
array = array.astype(float)
array.dtype

dtype('float64')

In [15]:
array = np.array(price)
array = array.astype(int)
# c. Append a new mobile having price of 13999 Rs. to this array

In [16]:
array = np.append(array,13999)
array

array([ 6999,  7500, 11999, 27899, 14999,  9999, 13999])

In [17]:
# d. Reverse this array of mobile phones prices
array = np.flip(array)
array

array([13999,  9999, 14999, 27899, 11999,  7500,  6999])

In [21]:
# e. Apply GST of 18% on mobile phones prices and update this array.
gst = 0.18
arr = array + (array * gst)
arr

array([19492.2076, 13922.6076, 20884.6076, 38846.5676, 16707.4076,
       10443.    ,  9745.4076])

In [31]:
# f. Sort the array in descending order of price
arr1 = np.sort(array)[::-1]
arr1

array([32920.82, 17698.82, 16518.82, 14158.82, 11798.82,  8850.  ,
        8258.82])

In [33]:
# g. What is the average mobile phone price
array = np.average(price)
array

np.float64(13232.5)

In [ ]:
# h. What is the difference b/w maximum and minimum price
