In [1]:
import numpy as np

In [2]:
# 12. Create a 3x3 array and a 1D array with 3 elements. Add the 1D array to the 2D array.
# Explain how broadcasting works in this operation.

arr1 = np.arange(1,10).reshape(3,3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
arr2 = np.array([10,20,30])
arr2

array([10, 20, 30])

In [5]:
arr1 + arr2             # broadcasting

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])