In [1]:
import numpy as np

In [2]:
# 8. Create two arrays of shape (2, 3): arr1 and arr2. Perform element-wise addition,
# subtraction, multiplication, and division on them.

arr1 = np.arange(1,7)
arr1

array([1, 2, 3, 4, 5, 6])

In [5]:
arr2 = np.arange(7,13)
arr2

array([ 7,  8,  9, 10, 11, 12])

In [6]:
arr1 + arr2

array([ 8, 10, 12, 14, 16, 18])

In [9]:
arr2 - arr1

array([6, 6, 6, 6, 6, 6])

In [10]:
arr1 * arr2

array([ 7, 16, 27, 40, 55, 72])

In [12]:
arr2 / arr1

array([7. , 4. , 3. , 2.5, 2.2, 2. ])