In [2]:
import numpy as np

In [3]:
# 10. Create a 2x2 matrix A and a 2x2 matrix B. Perform matrix multiplication using np.dot() or
# the @ operator.
A = np.arange(1,5).reshape(2,2)
A

array([[1, 2],
       [3, 4]])

In [4]:
B = np.arange(5,9).reshape(2,2)
B

array([[5, 6],
       [7, 8]])

In [5]:
mul = np.dot(A,B)
mul

array([[19, 22],
       [43, 50]])

In [6]:
A@B

array([[19, 22],
       [43, 50]])

In [9]:
# 11. Find the transpose of matrix A and matrix B. 

A_T = np.transpose(A)
B_T = np.transpose(B)

# Display results
print("Matrix A:\n", A)
print("Transpose of A:\n", A_T)

print("\nMatrix B:\n", B)
print("Transpose of B:\n", B_T)



Matrix A:
 [[1 2]
 [3 4]]
Transpose of A:
 [[1 3]
 [2 4]]

Matrix B:
 [[5 6]
 [7 8]]
Transpose of B:
 [[5 7]
 [6 8]]
